### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by EderSantana** [SeanNaren/QlearningExample.torch#1]
@SeanNaren would you suggest something to visualize the trained model? Maybe an extra script using display or another better way. Maybe in iTorch?

**Comment by SeanNaren** [comment]
Yep definitely! Going to try get some implementation done in iTorch, just getting my head around the module.

**Comment by SeanNaren** [comment]
Implementing the visual side of things opened up a much bigger issue, the model doesn't seem to converge nearly as well as your keras implementation, and the predictions always seem to be the same (a sequence of 1s or 2s or 3s). Trying to fix it now but any suggestions would be great!

**Comment by EderSantana** [comment]
ok, check it out without momentum. For instance, when I tried with adam it didn't work as well... 
It could be that. Also, you are using epsilon annealing. Have to check if that is going down to .1 fast enough since we are training only for 1000 epochs. I could be that. Not sure. Could you share the viz code so it is easier to debug?

**Comment by SeanNaren** [comment]
Added the basic visualisation code (uses itorch, currently I'm testing in notebook mode). Will try your suggestions out cheers!

**Comment by SeanNaren** [comment]
Wow that was a silly bug, the problem was that when I was updating the state based on the action, I was checking 0 1 2, rather than 1,2,3. After sorting this out, seems like the model is playing like a champ! Thanks for your help!

**Comment by EderSantana** [comment]
Great! I'm glad you get it figured!
